apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit-app
  ports:
  - port: 8501
    targetPort: 8501
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: neural-service
spec:
  selector:
    app: neural-service
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP